// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // -------------------------------------------------------------------------
  // Web
  // -------------------------------------------------------------------------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdbLUubvKltpOmILlmvGZmALd9e2bAUk0',
    appId: '1:926163440624:web:26dbb30884a3876a408335',
    messagingSenderId: '926163440624',
    projectId: 'doan-hotronuoiong',
    authDomain: 'doan-hotronuoiong.firebaseapp.com',
    storageBucket: 'doan-hotronuoiong.firebasestorage.app',
    measurementId: 'G-6K3WPGRRWH',
  );

  // -------------------------------------------------------------------------
  // Android - cap nhat theo google-services.json co SHA-1
  // mobilesdk_app_id: 1:926163440624:android:12be40982ae78d3d408335
  // package:         com.example.do_an_tot_nghiep_ho_tro_nuoi_ong
  // SHA-1:           05:DA:91:F6:2B:EE:A7:6C:09:6D:1E:07:27:36:12:6B:7F:EF:C0:3E
  // -------------------------------------------------------------------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGSw1Gh--doUiAt1Uixlezg5mGlKVJG1o',
    appId: '1:926163440624:android:12be40982ae78d3d408335',
    messagingSenderId: '926163440624',
    projectId: 'doan-hotronuoiong',
    storageBucket: 'doan-hotronuoiong.firebasestorage.app',
  );

  // -------------------------------------------------------------------------
  // iOS
  // -------------------------------------------------------------------------
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA_7xqNTon6gnD8c69ylmZtaXiLXQeSgU',
    appId: '1:926163440624:ios:fec5199784724a96408335',
    messagingSenderId: '926163440624',
    projectId: 'doan-hotronuoiong',
    storageBucket: 'doan-hotronuoiong.firebasestorage.app',
    iosBundleId: 'com.example.doAnTotNghiepHoTroNuoiOng',
  );
}
